# Generated by Django 4.0.5 on 2022-07-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='url',
            field=models.URLField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
