# Generated by Django 4.0.5 on 2022-07-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_platform_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='status',
        ),
    ]
